### ISSUE TITLE
Calificación mínima en filter_product

### ISSUE THREAD

**Issue by pitazzo** [unizar-30226-2019-08/Backend#101]
El filtrado excluye a los usuarios productos de los usuarios nuevos que todavía no tienen reseñas y tienen -1 como calificación. Quizás este comportamiento sea el deseable. /cc @elenamv13

**Comment by enrique-torres** [comment]
Se puede hacer así, o se pueden incluir en los resultados únicamente en caso de que la valoración mínima sea 0
