### ISSUE TITLE
Revisar valoraciones de usuario en el perfil de usuario

### ISSUE THREAD

**Issue by Cildoz98** [unizar-30226-2019-08/Backend#88]
El nombre del producto asociado a la valoración no es accesible

**Comment by Cildoz98** [comment]
Además, revisar el formato del timestamp ya que no es legible por humanos tal cual se manda ahora

**Comment by pitazzo** [comment]
En EINAmbiente hice esto para parsearla bonita: `"{{ cartel.fecha_fin_reto|date:"m-d-Y H:i:s" }}"`, había que instalar igual algo en Django. Yo prefiero timestamp para poder tratarlo a nuestro aire en móvil.

**Comment by Cildoz98** [comment]
Quizá hubiese que instalar algo porque yo no consigo formatearlo así

**Comment by pitazzo** [comment]
Había que
