### ISSUE TITLE
Serialización de /api/filter_products

### ISSUE THREAD

**Issue by pitazzo** [unizar-30226-2019-08/Backend#99]
La serialización de los productos devueltos por `api/filter_products` debería tener un formato similar a este (incluyendo lo solicitado en #98 ):

```
{
  "resultado" : [
	{
	    "producto" : {
	      ...
	      info producto sin nada del usuario
	      ...
	    }
	    "vendido_por" : {
	      ...
	      info del usuario
	      ...
	    }
	},
	{
		otro producto + usuario		
	},
	{
		otro producto + usuario		
	}
  ],
  "fin_paginacion" : true/false
}
```

**Comment by enrique-torres** [comment]
Ahora será así:
{
   "productos" : [
            {
                   "info_producto" : {
                            informacion del producto, con contenido multimedia pero sin usuario
                  },
                  "vendido_por" : {
	                    ...
	                   info del usuario
	                   ...
	          },
                  "le_gusta" : True o False
   ]
}

El filter products además devolverá (cuando esté la paginación implementada), un campo que indique si es la última página
